from typing import Protocol

from .models import Prediction, User


class UserRepository(Protocol):
    def get_by_username(self, username: str) -> User | None: ...
    def add(self, user: User) -> User: ...
    def get_by_id(self, user_id: int) -> User | None: ...


class PredictionRepository(Protocol):
    def add(self, prediction: Prediction) -> Prediction: ...
    def get_by_user(self, user_id: int) -> list[Prediction]: ...
